Repository DavidRomanovizc/DatingBot, pull requests merged in 2022-06, with the labels that each got.

#35 Dating v1.2dev RELEASE FIX + dev tree changes
  handlers/__init__.py
  handlers/admin/__init__.py
  handlers/admin/admin_handler.py
  handlers/users/__init__.py
  handlers/users/start_handler.py
  handlers/users/view_ques_handler.py
  keyboards/inline/questionnaires_inline.py
  utils/misc/create_questionnaire.py
Labels: fix, Improve structure

#39 keyboard rebuild
  data/config.py
  handlers/users/back_handler.py
  handlers/users/change_datas.py
  handlers/users/registration_handler.py
  handlers/users/second_menu.py
  handlers/users/start_handler.py
  handlers/users/support_handler.py
  handlers/users/verification_handler.py
  handlers/users/view_meetings_handler.py
  handlers/users/view_ques_handler.py
  keyboards/inline/filters_inline.py
  keyboards/inline/main_menu_inline.py
  keyboards/inline/meeting_inline.py
  keyboards/inline/menu_profile_inline.py
  keyboards/inline/second_menu_inline.py
Labels: difficult, Improve structure, Introduction of new functions

#44 #43🐛 Fix bug and edit menu
  functions/get_data_func.py
  functions/get_next_user_func.py
  functions/select_all_users_func.py
  functions/send_form_func.py
  handlers/users/back_handler.py
  handlers/users/change_datas.py
  handlers/users/registration_handler.py
  handlers/users/second_menu.py
  keyboards/inline/menu_profile_inline.py
Labels: bug, fix

#45 Dating v2.1dev
  brandbook/first_page.png
  brandbook/fourth_page.png
  brandbook/second_page.png
  brandbook/third_page.png
  functions/send_form_func.py
  handlers/users/__init__.py
  handlers/users/back_handler.py
  handlers/users/brandbook_handler.py
  handlers/users/meetings_handler.py
  handlers/users/registration_handler.py
  handlers/users/second_menu.py
  handlers/users/start_handler.py
  handlers/users/statistics.py
  handlers/users/support_handler.py
  handlers/users/view_ques_handler.py
  keyboards/inline/guide_inline.py
  keyboards/inline/meeting_inline.py
  keyboards/inline/menu_profile_inline.py
  utils/db_api/db_commands.py
Labels: documentation, fix, Introduction of new functions
