Repository DavidRomanovizc/DatingBot, pull requests merged in 2022-03, with the labels that each got.

#18 Mega refactor #make_dating_great_again
  .env.dist
  app.py
  data/locales/init
  django_project/telegrambot/usersmanage/models.py
  handlers/users/__init__.py
  handlers/users/back_handler.py
  handlers/users/change_datas.py
  handlers/users/echo.py
  handlers/users/find_handlers.py
  handlers/users/menu.py
  handlers/users/registration.py
  handlers/users/report.py
  handlers/users/start.py
  handlers/users/statistics.py
  handlers/users/ucasse_buy.py
  handlers/users/view.py
  keyboards/default/change_profile_inline.py
  keyboards/inline/guide_btn.py
  keyboards/inline/lifestyle_choice_inline.py
  keyboards/inline/second_menu.py
Labels: fix, Improve structure, Introduction of new functions

#20 refactor again + delete fukin trash
  handlers/users/__init__.py
  handlers/users/change_datas.py
  handlers/users/find_handlers.py
  handlers/users/qiwi_buy.py
  handlers/users/statistics.py
  handlers/users/ucasse_buy.py
  keyboards/default/change_profile_text.py
  keyboards/inline/Primer.py
  keyboards/inline/change_keyboard.py
Labels: fix, Improve structure

#21 Fixed bugs, improved methods of sending messages, deleted unused files, rewritten buttons, added new features
  .env.dist
  app.py
  data/config.py
  data/subs.py
  handlers/users/__init__.py
  handlers/users/admin.py
  handlers/users/back_handler.py
  handlers/users/change_datas.py
  handlers/users/information.py
  handlers/users/menu.py
  handlers/users/registration.py
  handlers/users/report.py
  handlers/users/start.py
  handlers/users/statistics.py
  handlers/users/view.py
  keyboards/default/change_profile_text.py
  keyboards/inline/BN_report.py
  keyboards/inline/back_bnt.py
  keyboards/inline/change_button.py
  keyboards/inline/change_data_profile.py
  keyboards/inline/guide_btn.py
  keyboards/inline/lifestyle_choice_inline.py
  keyboards/inline/main_menu.py
  keyboards/inline/profile_bt.py
  keyboards/inline/questionnaires_inline.py
  keyboards/inline/second_menu.py
  keyboards/inline/sex_partner.py
  middlewares/throttling.py
  utils/misc/ds_name.py
  utils/misc/qiwi.py
Labels: enhancement, good first issue, fix, Improve structure, Introduction of new functions

#22 ♻️ Refactor code and add new buttons
  handlers/users/__init__.py
  handlers/users/menu.py
  handlers/users/registration.py
  handlers/users/send_report.py
  handlers/users/view_ques.py
  keyboards/inline/second_menu.py
Labels: fix

#23 Change button in main menu, added support .etc
  data/config.py
  handlers/users/__init__.py
  handlers/users/back_handler.py
  handlers/users/change_datas.py
  handlers/users/filters_handler.py
  handlers/users/information.py
  handlers/users/menu.py
  handlers/users/registration.py
  handlers/users/send_report.py
  handlers/users/start.py
  handlers/users/statistics.py
  handlers/users/support_handler.py
  handlers/users/view_ques.py
  keyboards/inline/change_data_profile_inline.py
  keyboards/inline/change_inline.py
  keyboards/inline/filters_inline.py
  keyboards/inline/gender_inline.py
  keyboards/inline/guide_inline.py
  keyboards/inline/main_menu_inline.py
  keyboards/inline/profile_inline.py
  keyboards/inline/report_inline.py
  keyboards/inline/second_menu_inline.py
  keyboards/inline/support_inline.py
  middlewares/__init__.py
  middlewares/agent_support.py
Labels: Improve structure, Introduction of new functions
